name: Deploy WordPress Plugin

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Validate PHP syntax
      run: find . -name "*.php" -exec php -l {} \;

    - name: Zip plugin
      run: |
        PLUGIN_DIR=$(basename ${{ github.repository }})
        mkdir -p ./dist
        zip -r "./dist/${PLUGIN_DIR}.zip" . -x ".git/*" ".github/*" "tests/*" ".git*"

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
